from __future__ import annotations

from dataclasses import asdict, dataclass


@dataclass(frozen=True)
class MetricDefinition:
    id: str
    name: str
    entity_types: tuple[str, ...]
    unit: str
    kind: str
    source: str
    minimum_interval_seconds: int
    capability: str | None
    retention_class: str
    aggregation: str
    availability: str
    formula: str | None
    test_evidence: str
    implementation_status: str
    physical_validation: str

    def document(self) -> dict[str, object]:
        return asdict(self)


def _m(
    metric_id: str,
    name: str,
    entities: str,
    unit: str,
    *,
    source: str,
    interval: int = 5,
    capability: str | None = None,
    retention: str = "recent",
    aggregation: str = "mean",
    formula: str | None = None,
    evidence: str = "backend/tests/test_enterprise_telemetry.py",
) -> MetricDefinition:
    provider_dependent = any(
        token in source.casefold()
        for token in (
            "smart",
            "nvme",
            "provider",
            "ses/",
            "multipath",
            "fc ",
        )
    )
    physical_validation_pending = provider_dependent or metric_id == "multipath.failovers"
    return MetricDefinition(
        id=metric_id,
        name=name,
        entity_types=tuple(entities.split("|")),
        unit=unit,
        kind="derived" if formula else "raw",
        source=source,
        minimum_interval_seconds=interval,
        capability=capability,
        retention_class=retention,
        aggregation=aggregation,
        availability="When the named local source/provider reports the value",
        formula=formula,
        test_evidence=evidence,
        implementation_status=(
            "SUPPORTED WHEN PROVIDER REPORTS VALUE"
            if provider_dependent
            else "PRODUCTION IMPLEMENTED + SOFTWARE VERIFIED"
        ),
        physical_validation="pending" if physical_validation_pending else "not_required",
    )


METRICS: tuple[MetricDefinition, ...] = (
    _m("host.cpu.utilization", "Processor utilization", "host", "percent", source="psutil"),
    _m("host.load.1m", "Load average (1 minute)", "host", "count", source="os.getloadavg"),
    _m("host.load.5m", "Load average (5 minutes)", "host", "count", source="os.getloadavg"),
    _m("host.load.15m", "Load average (15 minutes)", "host", "count", source="os.getloadavg"),
    _m("host.memory.used", "Memory used", "host", "bytes", source="psutil"),
    _m("host.memory.available", "Memory available", "host", "bytes", source="psutil"),
    _m("host.memory.utilization", "Memory utilization", "host", "percent", source="psutil"),
    _m("host.swap.utilization", "Swap utilization", "host", "percent", source="psutil"),
    _m("host.uptime", "Host uptime", "host", "seconds", source="psutil", aggregation="last"),
    _m(
        "capacity.total",
        "Total capacity",
        "host|pool|filesystem|mount|storage_tier|mergerfs_pool",
        "bytes",
        source="statvfs/provider",
        interval=60,
        aggregation="last",
    ),
    _m(
        "capacity.used",
        "Used capacity",
        "host|pool|filesystem|mount|storage_tier|mergerfs_pool",
        "bytes",
        source="statvfs/provider",
        interval=60,
        aggregation="last",
    ),
    _m(
        "capacity.free",
        "Free capacity",
        "host|pool|filesystem|mount|storage_tier|mergerfs_pool",
        "bytes",
        source="statvfs/provider",
        interval=60,
        aggregation="last",
    ),
    _m(
        "capacity.utilization",
        "Capacity utilization",
        "host|pool|filesystem|mount|storage_tier|mergerfs_pool",
        "percent",
        source="statvfs/provider",
        interval=60,
        aggregation="last",
    ),
    _m(
        "storage.raw_capacity",
        "Raw storage capacity",
        "host",
        "bytes",
        source="hardware inventory",
        interval=300,
        aggregation="last",
    ),
    _m(
        "storage.unallocated_capacity",
        "Unallocated capacity",
        "host",
        "bytes",
        source="storage inventory",
        interval=300,
        aggregation="last",
    ),
    _m(
        "io.read.bytes_per_second",
        "Read throughput",
        "host|drive|pool|vdev|filesystem|mount|storage_tier|multipath_device|storage_path|iscsi_lun",
        "bytes_per_second",
        source="Linux/provider counters",
        aggregation="mean",
    ),
    _m(
        "io.write.bytes_per_second",
        "Write throughput",
        "host|drive|pool|vdev|filesystem|mount|storage_tier|multipath_device|storage_path|iscsi_lun",
        "bytes_per_second",
        source="Linux/provider counters",
        aggregation="mean",
    ),
    _m(
        "io.read.iops",
        "Read IOPS",
        "host|drive|pool|vdev|filesystem|mount|storage_tier|multipath_device|storage_path|iscsi_lun",
        "operations_per_second",
        source="Linux/provider counters",
    ),
    _m(
        "io.write.iops",
        "Write IOPS",
        "host|drive|pool|vdev|filesystem|mount|storage_tier|multipath_device|storage_path|iscsi_lun",
        "operations_per_second",
        source="Linux/provider counters",
    ),
    _m(
        "io.read.latency",
        "Read response time",
        "host|drive|pool|vdev|storage_path",
        "milliseconds",
        source="Linux/provider counters",
    ),
    _m(
        "io.write.latency",
        "Write response time",
        "host|drive|pool|vdev|storage_path",
        "milliseconds",
        source="Linux/provider counters",
    ),
    _m(
        "io.utilization",
        "Storage utilization",
        "host|drive|pool|vdev|storage_path",
        "percent",
        source="Linux/provider counters",
    ),
    _m(
        "io.queue.depth",
        "Queue depth",
        "drive|controller|hba|storage_path|pool",
        "count",
        source="sysfs/provider counters",
    ),
    _m(
        "io.busy_time",
        "Busy time",
        "drive|controller|nvme_device",
        "milliseconds",
        source="Linux/provider counters",
    ),
    _m(
        "io.weighted_time",
        "Weighted I/O time",
        "drive",
        "milliseconds",
        source="Linux diskstats",
        capability="metrics.drive.advanced",
    ),
    _m(
        "io.read.today",
        "Reads today",
        "drive|pool|storage_tier",
        "bytes",
        source="reset-safe local counter baseline",
        capability="metrics.drive.advanced",
        aggregation="last",
    ),
    _m(
        "io.write.today",
        "Writes today",
        "drive|pool|storage_tier",
        "bytes",
        source="reset-safe local counter baseline",
        aggregation="last",
    ),
    _m(
        "network.link.up",
        "Link state",
        "network_interface|network_bond",
        "boolean",
        source="psutil/sysfs",
        aggregation="last",
    ),
    _m(
        "network.link.speed",
        "Negotiated link speed",
        "network_interface|network_bond|fc_port|fcoe_path",
        "bits_per_second",
        source="psutil/sysfs/provider",
        aggregation="last",
    ),
    _m(
        "network.receive.bytes_per_second",
        "Receive throughput",
        "network_interface|network_bond|fc_port|fcoe_path",
        "bytes_per_second",
        source="Linux/provider counters",
    ),
    _m(
        "network.transmit.bytes_per_second",
        "Transmit throughput",
        "network_interface|network_bond|fc_port|fcoe_path",
        "bytes_per_second",
        source="Linux/provider counters",
    ),
    _m(
        "network.receive.packets_per_second",
        "Receive packet rate",
        "network_interface|network_bond",
        "packets_per_second",
        source="Linux counters",
    ),
    _m(
        "network.transmit.packets_per_second",
        "Transmit packet rate",
        "network_interface|network_bond",
        "packets_per_second",
        source="Linux counters",
    ),
    _m(
        "network.errors",
        "Interface errors",
        "network_interface|network_bond|fc_port|fcoe_path",
        "count",
        source="Linux/provider counters",
        aggregation="max",
    ),
    _m(
        "network.drops",
        "Interface drops",
        "network_interface|network_bond",
        "count",
        source="Linux counters",
        aggregation="max",
    ),
    _m(
        "health.overall",
        "Health state",
        "drive|controller|hba|enclosure|slot|pool|vdev|md_array|multipath_device|storage_path|fc_port|fcoe_path|service",
        "state",
        source="SMART/provider",
        interval=300,
        aggregation="last",
    ),
    _m(
        "drive.temperature",
        "Drive temperature",
        "drive|nvme_device",
        "celsius",
        source="SMART/NVMe",
        interval=300,
    ),
    _m(
        "drive.power_on_hours",
        "Power-on hours",
        "drive|nvme_device",
        "hours",
        source="SMART/NVMe",
        interval=300,
        aggregation="last",
    ),
    _m(
        "drive.reallocated_sectors",
        "Reallocated sectors",
        "drive",
        "count",
        source="SMART",
        interval=300,
        aggregation="max",
    ),
    _m(
        "drive.pending_sectors",
        "Pending sectors",
        "drive",
        "count",
        source="SMART",
        interval=300,
        aggregation="max",
    ),
    _m(
        "drive.uncorrectable_sectors",
        "Uncorrectable sectors",
        "drive",
        "count",
        source="SMART",
        interval=300,
        aggregation="max",
    ),
    _m(
        "drive.media_errors",
        "Media/data integrity errors",
        "drive|nvme_device",
        "count",
        source="SMART/NVMe",
        interval=300,
        aggregation="max",
    ),
    _m(
        "drive.nvme.critical_warning",
        "NVMe critical warning",
        "drive|nvme_device",
        "bitmask",
        source="NVMe SMART",
        interval=300,
        aggregation="max",
    ),
    _m(
        "drive.interface_crc_errors",
        "Interface CRC errors",
        "drive|storage_path",
        "count",
        source="SMART/provider",
        interval=300,
        capability="metrics.drive.advanced",
        aggregation="max",
    ),
    _m(
        "drive.command_timeouts",
        "Command timeouts",
        "drive|controller",
        "count",
        source="SMART/provider",
        interval=300,
        capability="metrics.drive.advanced",
        aggregation="max",
    ),
    _m(
        "drive.unsafe_shutdowns",
        "Unsafe shutdowns",
        "nvme_device|drive",
        "count",
        source="NVMe SMART",
        interval=300,
        aggregation="max",
    ),
    _m(
        "drive.percentage_used",
        "SSD percentage used",
        "drive|nvme_device",
        "percent",
        source="SMART/NVMe",
        interval=300,
        aggregation="max",
    ),
    _m(
        "drive.endurance_remaining",
        "SSD endurance remaining",
        "drive|nvme_device",
        "percent",
        source="SMART/NVMe",
        interval=300,
        aggregation="last",
    ),
    _m(
        "drive.available_spare",
        "NVMe available spare",
        "nvme_device|drive",
        "percent",
        source="NVMe SMART",
        interval=300,
        capability="metrics.drive.advanced",
        aggregation="last",
    ),
    _m(
        "drive.available_spare_threshold",
        "NVMe spare threshold",
        "nvme_device|drive",
        "percent",
        source="NVMe SMART",
        interval=300,
        capability="metrics.drive.advanced",
        aggregation="last",
    ),
    _m(
        "drive.lifetime_host_writes",
        "Lifetime host writes",
        "drive|nvme_device",
        "bytes",
        source="SMART/NVMe",
        interval=300,
        aggregation="max",
    ),
    _m(
        "drive.lifetime_host_reads",
        "Lifetime host reads",
        "drive|nvme_device",
        "bytes",
        source="SMART/NVMe",
        interval=300,
        capability="metrics.drive.advanced",
        aggregation="max",
    ),
    _m(
        "drive.nvme.controller_busy_time",
        "NVMe controller busy time",
        "nvme_device",
        "minutes",
        source="NVMe SMART",
        interval=300,
        capability="metrics.drive.advanced",
        aggregation="max",
    ),
    _m(
        "drive.nvme.power_cycles",
        "NVMe power cycles",
        "nvme_device",
        "count",
        source="NVMe SMART",
        interval=300,
        capability="metrics.drive.advanced",
        aggregation="max",
    ),
    _m(
        "drive.nvme.error_log_entries",
        "NVMe error log entries",
        "nvme_device",
        "count",
        source="NVMe SMART",
        interval=300,
        capability="metrics.drive.advanced",
        aggregation="max",
    ),
    _m(
        "controller.temperature",
        "Controller temperature",
        "controller|hba",
        "celsius",
        source="controller provider",
        interval=300,
        capability="metrics.controller.advanced",
    ),
    _m(
        "controller.cache.hit_ratio",
        "Controller cache hit ratio",
        "controller",
        "ratio",
        source="controller provider",
        interval=300,
        capability="metrics.controller.advanced",
    ),
    _m(
        "controller.cache.state",
        "Controller cache state",
        "controller",
        "state",
        source="controller provider",
        interval=300,
        capability="metrics.controller.advanced",
        aggregation="last",
    ),
    _m(
        "controller.battery.state",
        "Controller battery state",
        "controller",
        "state",
        source="controller provider",
        interval=300,
        capability="metrics.controller.advanced",
        aggregation="last",
    ),
    _m(
        "sas.phy.invalid_dwords",
        "SAS PHY invalid DWORDs",
        "storage_path|sas_expander",
        "count",
        source="SAS provider",
        interval=300,
        capability="metrics.controller.advanced",
        aggregation="max",
    ),
    _m(
        "sas.phy.disparity_errors",
        "SAS PHY disparity errors",
        "storage_path|sas_expander",
        "count",
        source="SAS provider",
        interval=300,
        capability="metrics.controller.advanced",
        aggregation="max",
    ),
    _m(
        "enclosure.temperature",
        "Enclosure temperature",
        "enclosure|slot",
        "celsius",
        source="SES/provider",
        interval=300,
        capability="metrics.controller.advanced",
    ),
    _m(
        "enclosure.fan.speed",
        "Enclosure fan speed",
        "enclosure",
        "rpm",
        source="SES/provider",
        interval=300,
        capability="metrics.controller.advanced",
    ),
    _m(
        "enclosure.path.redundancy",
        "Enclosure active paths",
        "enclosure",
        "count",
        source="SES/multipath provider",
        interval=60,
        capability="metrics.controller.advanced",
        aggregation="last",
    ),
    _m(
        "pool.fragmentation",
        "ZFS fragmentation",
        "pool",
        "percent",
        source="zpool",
        interval=60,
        capability="metrics.pool.advanced",
    ),
    _m(
        "pool.scrub.progress",
        "Scrub progress",
        "pool|md_array|snapraid_configuration",
        "percent",
        source="pool provider",
        interval=30,
        aggregation="last",
    ),
    _m(
        "pool.rebuild.progress",
        "Rebuild/resilver progress",
        "pool|vdev|md_array",
        "percent",
        source="pool provider",
        interval=30,
        aggregation="last",
    ),
    _m(
        "pool.members.active",
        "Active members",
        "md_array|pool|snapraid_configuration|mergerfs_pool",
        "count",
        source="pool provider",
        interval=30,
        capability="metrics.pool.advanced",
        aggregation="last",
    ),
    _m(
        "pool.members.failed",
        "Failed members",
        "md_array|pool|snapraid_configuration|mergerfs_pool",
        "count",
        source="pool provider",
        interval=30,
        aggregation="last",
    ),
    _m(
        "pool.members.spare",
        "Spare members",
        "md_array|pool",
        "count",
        source="pool provider",
        interval=30,
        capability="metrics.pool.advanced",
        aggregation="last",
    ),
    _m(
        "pool.errors.read",
        "Pool read errors",
        "pool|vdev|md_array|snapraid_configuration",
        "count",
        source="pool provider",
        interval=30,
        aggregation="max",
    ),
    _m(
        "pool.errors.write",
        "Pool write errors",
        "pool|vdev|md_array|snapraid_configuration",
        "count",
        source="pool provider",
        interval=30,
        aggregation="max",
    ),
    _m(
        "pool.errors.checksum",
        "Pool checksum errors",
        "pool|vdev|snapraid_configuration",
        "count",
        source="pool provider",
        interval=30,
        aggregation="max",
    ),
    _m(
        "fc.link.failures",
        "Fibre Channel link failures",
        "fc_port|fcoe_path",
        "count",
        source="FC sysfs",
        interval=30,
        capability="metrics.network.advanced",
        aggregation="max",
    ),
    _m(
        "fc.loss.of.signal",
        "Fibre Channel loss of signal",
        "fc_port|fcoe_path",
        "count",
        source="FC sysfs",
        interval=30,
        capability="metrics.network.advanced",
        aggregation="max",
    ),
    _m(
        "fc.loss.of.sync",
        "Fibre Channel loss of synchronization",
        "fc_port|fcoe_path",
        "count",
        source="FC sysfs",
        interval=30,
        capability="metrics.network.advanced",
        aggregation="max",
    ),
    _m(
        "zfs.arc.size",
        "ZFS ARC size",
        "host|pool",
        "bytes",
        source="/proc/spl/kstat/zfs/arcstats",
        interval=30,
        capability="metrics.pool.advanced",
    ),
    _m(
        "zfs.arc.hit_ratio",
        "ZFS ARC hit ratio",
        "host|pool",
        "ratio",
        source="ZFS ARC counters",
        interval=30,
        capability="metrics.pool.advanced",
        formula="hits / (hits + misses) when both native counters are available",
    ),
    _m(
        "mergerfs.distribution.imbalance",
        "mergerFS free-space imbalance",
        "mergerfs_pool",
        "percent",
        source="member statvfs",
        interval=60,
        capability="metrics.pool.advanced",
        formula="(maximum member utilization - minimum member utilization) percentage points",
    ),
    _m(
        "multipath.paths.active",
        "Active storage paths",
        "multipath_device",
        "count",
        source="multipathd",
        interval=30,
        capability="metrics.network.advanced",
        aggregation="last",
    ),
    _m(
        "multipath.paths.failed",
        "Failed storage paths",
        "multipath_device",
        "count",
        source="multipathd",
        interval=30,
        capability="metrics.network.advanced",
        aggregation="last",
    ),
    _m(
        "multipath.failovers",
        "Storage path failovers",
        "multipath_device",
        "count",
        source="stored path-state transitions",
        interval=30,
        capability="metrics.network.advanced",
        aggregation="max",
    ),
    _m(
        "tier.occupancy",
        "Fast-tier occupancy",
        "storage_tier",
        "percent",
        source="tier capacity",
        interval=30,
    ),
    _m(
        "tier.bytes_moved",
        "Bytes moved to media tier",
        "storage_tier",
        "bytes",
        source="durable transfer operations",
        interval=30,
        capability="metrics.analytics.workload",
        aggregation="max",
    ),
    _m(
        "tier.transfer.failures",
        "Tier transfer failures",
        "storage_tier",
        "count",
        source="durable transfer operations",
        interval=30,
        capability="metrics.analytics.workload",
        aggregation="max",
    ),
    _m(
        "tier.transfers.completed",
        "Tier transfers completed",
        "storage_tier",
        "count",
        source="durable transfer operations",
        interval=30,
        capability="metrics.analytics.workload",
        aggregation="max",
    ),
    _m(
        "tier.transfers.pending",
        "Tier transfers pending",
        "storage_tier",
        "count",
        source="durable transfer operations",
        interval=30,
        aggregation="last",
    ),
    _m(
        "tier.space.recoverable",
        "Space recoverable after seeding",
        "storage_tier",
        "bytes",
        source="retained torrent transfer operations",
        interval=30,
        capability="metrics.analytics.workload",
        aggregation="last",
    ),
    _m(
        "tier.hardlink.ratio",
        "Hardlink transfer ratio",
        "storage_tier",
        "ratio",
        source="durable transfer operations",
        interval=30,
        capability="metrics.analytics.workload",
        formula="completed hardlink transfers / completed transfers",
    ),
    _m(
        "analytics.latency.p50",
        "Latency P50",
        "drive|pool|vdev|storage_path",
        "milliseconds",
        source="stored observations",
        interval=60,
        capability="metrics.analytics.performance",
        retention="extended",
        formula="nearest-rank 50th percentile from sufficient observations",
    ),
    _m(
        "analytics.latency.p95",
        "Latency P95",
        "drive|pool|vdev|storage_path",
        "milliseconds",
        source="stored observations",
        interval=60,
        capability="metrics.analytics.performance",
        retention="extended",
        formula="nearest-rank 95th percentile from sufficient observations",
    ),
    _m(
        "analytics.latency.p99",
        "Latency P99",
        "drive|pool|vdev|storage_path",
        "milliseconds",
        source="stored observations",
        interval=60,
        capability="metrics.analytics.performance",
        retention="extended",
        formula="nearest-rank 99th percentile from sufficient observations",
    ),
    _m(
        "analytics.capacity.growth_rate",
        "Capacity growth rate",
        "host|pool|filesystem|mount|mergerfs_pool",
        "bytes_per_day",
        source="stored capacity observations",
        interval=3600,
        capability="metrics.analytics.capacity",
        retention="extended",
        formula="Theil-Sen median slope over sufficient daily observations",
    ),
    _m(
        "analytics.endurance.consumption_rate",
        "Endurance consumption rate",
        "drive|nvme_device",
        "percent_per_day",
        source="stored wear observations",
        interval=3600,
        capability="metrics.analytics.endurance",
        retention="extended",
        formula="Theil-Sen median slope of reported percentage used",
    ),
    _m(
        "analytics.workload.read_ratio",
        "Read ratio",
        "drive|pool|storage_tier",
        "ratio",
        source="stored throughput observations",
        interval=60,
        capability="metrics.analytics.workload",
        formula="read bytes / (read bytes + write bytes)",
    ),
)

CATALOG_BY_ID = {item.id: item for item in METRICS}
if len(CATALOG_BY_ID) != len(METRICS):
    raise RuntimeError("metric catalog contains duplicate IDs")


def catalog_document() -> list[dict[str, object]]:
    return [item.document() for item in METRICS]
