"""initial fleet ingestion schema

Revision ID: 0001
Revises:
Create Date: 2026-08-24 08:25:01.364955
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fleet_central_maintenance",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fleet_drives",
        sa.Column("drive_id", sa.String(length=64), nullable=False),
        sa.Column("identity_version", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("drive_id"),
    )
    op.create_table(
        "fleet_installations",
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("credential_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("credential_fingerprint", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("platform_family", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("last_sequence_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("installation_id"),
    )
    op.create_table(
        "fleet_application_observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("product", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fleet_application_observations_installation_id"),
        "fleet_application_observations",
        ["installation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fleet_application_observations_product"),
        "fleet_application_observations",
        ["product"],
        unique=False,
    )
    op.create_table(
        "fleet_capacity_observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fleet_capacity_observations_installation_id"),
        "fleet_capacity_observations",
        ["installation_id"],
        unique=False,
    )
    op.create_table(
        "fleet_category_observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_fleet_category_kind_time",
        "fleet_category_observations",
        ["kind", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fleet_category_observations_installation_id"),
        "fleet_category_observations",
        ["installation_id"],
        unique=False,
    )
    op.create_table(
        "fleet_controller_observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fleet_controller_observations_installation_id"),
        "fleet_controller_observations",
        ["installation_id"],
        unique=False,
    )
    op.create_table(
        "fleet_drive_lifecycle_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("drive_id", sa.String(length=64), nullable=True),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fleet_drive_lifecycle_events_drive_id"),
        "fleet_drive_lifecycle_events",
        ["drive_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fleet_drive_lifecycle_events_installation_id"),
        "fleet_drive_lifecycle_events",
        ["installation_id"],
        unique=False,
    )
    op.create_table(
        "fleet_drive_observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("drive_id", sa.String(length=64), nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drive_id"],
            ["fleet_drives.drive_id"],
        ),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_fleet_drive_observation_drive_time",
        "fleet_drive_observations",
        ["drive_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fleet_drive_observations_installation_id"),
        "fleet_drive_observations",
        ["installation_id"],
        unique=False,
    )
    op.create_table(
        "fleet_feature_usage_observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("feature", sa.String(length=96), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fleet_feature_usage_observations_feature"),
        "fleet_feature_usage_observations",
        ["feature"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fleet_feature_usage_observations_installation_id"),
        "fleet_feature_usage_observations",
        ["installation_id"],
        unique=False,
    )
    op.create_table(
        "fleet_geographic_settings",
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("timezone", sa.String(length=128), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("installation_id"),
    )
    op.create_table(
        "fleet_hardware_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("system_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fleet_hardware_snapshots_installation_id"),
        "fleet_hardware_snapshots",
        ["installation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fleet_hardware_snapshots_observed_at"),
        "fleet_hardware_snapshots",
        ["observed_at"],
        unique=False,
    )
    op.create_table(
        "fleet_ingested_batches",
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("batch_id"),
        sa.UniqueConstraint("installation_id", "sequence_number"),
    )
    op.create_index(
        op.f("ix_fleet_ingested_batches_installation_id"),
        "fleet_ingested_batches",
        ["installation_id"],
        unique=False,
    )
    op.create_table(
        "fleet_installation_heartbeats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("platform_family", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_fleet_heartbeats_installation_time",
        "fleet_installation_heartbeats",
        ["installation_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "fleet_storage_layout_observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fleet_storage_layout_observations_installation_id"),
        "fleet_storage_layout_observations",
        ["installation_id"],
        unique=False,
    )
    op.create_table(
        "fleet_version_observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fleet_version_observations_version"),
        "fleet_version_observations",
        ["version"],
        unique=False,
    )
    op.create_table(
        "fleet_ingested_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("record_id", sa.String(length=36), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("message_type", sa.String(length=32), nullable=False),
        sa.Column("telemetry_level", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["fleet_ingested_batches.batch_id"],
        ),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["fleet_installations.installation_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("installation_id", "record_id"),
    )
    op.create_index(
        op.f("ix_fleet_ingested_records_installation_id"),
        "fleet_ingested_records",
        ["installation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fleet_ingested_records_installation_id"), table_name="fleet_ingested_records"
    )
    op.drop_table("fleet_ingested_records")
    op.drop_index(
        op.f("ix_fleet_version_observations_version"), table_name="fleet_version_observations"
    )
    op.drop_table("fleet_version_observations")
    op.drop_index(
        op.f("ix_fleet_storage_layout_observations_installation_id"),
        table_name="fleet_storage_layout_observations",
    )
    op.drop_table("fleet_storage_layout_observations")
    op.drop_index(
        "ix_fleet_heartbeats_installation_time", table_name="fleet_installation_heartbeats"
    )
    op.drop_table("fleet_installation_heartbeats")
    op.drop_index(
        op.f("ix_fleet_ingested_batches_installation_id"), table_name="fleet_ingested_batches"
    )
    op.drop_table("fleet_ingested_batches")
    op.drop_index(
        op.f("ix_fleet_hardware_snapshots_observed_at"), table_name="fleet_hardware_snapshots"
    )
    op.drop_index(
        op.f("ix_fleet_hardware_snapshots_installation_id"), table_name="fleet_hardware_snapshots"
    )
    op.drop_table("fleet_hardware_snapshots")
    op.drop_table("fleet_geographic_settings")
    op.drop_index(
        op.f("ix_fleet_feature_usage_observations_installation_id"),
        table_name="fleet_feature_usage_observations",
    )
    op.drop_index(
        op.f("ix_fleet_feature_usage_observations_feature"),
        table_name="fleet_feature_usage_observations",
    )
    op.drop_table("fleet_feature_usage_observations")
    op.drop_index(
        op.f("ix_fleet_drive_observations_installation_id"), table_name="fleet_drive_observations"
    )
    op.drop_index("ix_fleet_drive_observation_drive_time", table_name="fleet_drive_observations")
    op.drop_table("fleet_drive_observations")
    op.drop_index(
        op.f("ix_fleet_drive_lifecycle_events_installation_id"),
        table_name="fleet_drive_lifecycle_events",
    )
    op.drop_index(
        op.f("ix_fleet_drive_lifecycle_events_drive_id"), table_name="fleet_drive_lifecycle_events"
    )
    op.drop_table("fleet_drive_lifecycle_events")
    op.drop_index(
        op.f("ix_fleet_controller_observations_installation_id"),
        table_name="fleet_controller_observations",
    )
    op.drop_table("fleet_controller_observations")
    op.drop_index(
        op.f("ix_fleet_category_observations_installation_id"),
        table_name="fleet_category_observations",
    )
    op.drop_index("ix_fleet_category_kind_time", table_name="fleet_category_observations")
    op.drop_table("fleet_category_observations")
    op.drop_index(
        op.f("ix_fleet_capacity_observations_installation_id"),
        table_name="fleet_capacity_observations",
    )
    op.drop_table("fleet_capacity_observations")
    op.drop_index(
        op.f("ix_fleet_application_observations_product"),
        table_name="fleet_application_observations",
    )
    op.drop_index(
        op.f("ix_fleet_application_observations_installation_id"),
        table_name="fleet_application_observations",
    )
    op.drop_table("fleet_application_observations")
    op.drop_table("fleet_installations")
    op.drop_table("fleet_drives")
    op.drop_table("fleet_central_maintenance")
    # ### end Alembic commands ###
